# Generated by Django 5.1.1 on 2024-09-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('transport_price', models.CharField(max_length=50)),
                ('advance_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('license_plate', models.CharField(max_length=50)),
                ('cargo_owner', models.CharField(max_length=255)),
                ('cargo_owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('loading_date', models.DateField()),
                ('unloading_date', models.DateField()),
                ('remaining_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transportation',
                'verbose_name_plural': 'Transportations',
                'db_table': 'transportation',
            },
        ),
    ]
