# Generated by Django 5.1.1 on 2024-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='cargo_owner_phone',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='comments',
        ),
        migrations.AddField(
            model_name='transportation',
            name='additional',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='business_trip',
            field=models.TextField(blank=True, null=True, verbose_name='Kомандировичный'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='advance_payment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аванс'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='cargo_owner',
            field=models.CharField(max_length=255, verbose_name='Владелец груза'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='license_plate',
            field=models.CharField(max_length=50, verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='loading_date',
            field=models.DateField(verbose_name='Дата Погрузки'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='remaining_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому Оплачен'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='route',
            field=models.CharField(max_length=255, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='transport_price',
            field=models.CharField(max_length=50, verbose_name='Цена перевозки'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='unloading_date',
            field=models.DateField(verbose_name='Дата Выгрузки'),
        ),
    ]
