# Generated by Django 5.1.1 on 2024-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_transportation_created_alter_transportation_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='paid_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому Оплачен'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='remaining_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Остаток'),
        ),
    ]
