# Generated by Django 5.1.1 on 2024-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_alter_transportation_cargo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='status',
            field=models.CharField(choices=[('warning', 'В ожидании'), ('success', 'Выполнено'), ('danger', 'Отменено')], default='warning', max_length=7, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
